spring.application.name=ExamanJEE

server.port=8085
spring.datasource.url=jdbc:mysql://localhost:3306/Assurence?createDatabaseIfNotExist=true


spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true

# Chemin pour l'interface UI de Swagger
springdoc.swagger-ui.path=/swagger-ui.html
# Chemin pour la spécification OpenAPI au format JSON
springdoc.api-docs.path=/v3/api-docs
spring.security.user.password=ouardia12345678
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.security.oauth2=DEBUG
#jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
